### PR TITLE
Cause NameError in .constantize if empty input given (#6)

### PR DESCRIPTION
**Pull request by Ptico**

### CODE REVIEW

**Comment by mbj** [comment]
@Ptico I just realize the CI is not green on that one. I cannot release it with that state. Likely it needs get ported to Circle.

**Comment by Ptico** [comment]
@mbj do you mean #8 ? I think you need to reactivate Travis somehow

**Comment by mbj** [comment]
@Ptico I think we should port this to circle instead.

And yes I meant #8, sorry.

**Comment by Ptico** [comment]
@mbj ok, please, let me know when it will be ready and i will try to help with #12

**Comment by mbj** [comment]
@Ptico I do not plan to do it by myself, since I've close to 0 OSS time, and inflecto is low on my priority list. Do you want to take it?

**Comment by Ptico** [comment]
Why not, let me take a look: this one? https://circleci.com

**Comment by mbj** [comment]
@Ptico yes, that is the one I use right now for all my OSS projects.

**Pull request merged**
