### PR TITLE
Provide optional refinements for String and Numeric

### PR DESCRIPTION
**Pull request by alsemyonov**
It does not change the behavior of any classes by default.
But it allows using modern Ruby feature on supported Ruby versions.

``` ruby
using Inflecto::Refinements

'sample'.pluralize #=> 'samples'
1.ordinalize #=> '1st'
```

### CODE REVIEW

**Comment by alsemyonov** [comment]
The first commit does not belong here, but without it, I was not able to run `bundle` successfully using the modern `bundler` version.

**Comment by mbj** [comment]
> The first commit does not belong here, but without it, I was not able to run bundle successfully using the modern bundler version.

Can you PR that in separate?

**Comment by alsemyonov** [comment]
Done in #15.

**Comment by alsemyonov** [comment]
I have changed the method whether refinements should be required to check the version of Ruby instead of relying on actually undefined method `refine` and provided specs for refined String and Numeric classes.

**Comment by mbj** [comment]
@alsemyonov Thx for your work. But I do consider refinements as a ruby feature, and supporting refinements in a generic library a mistake. I've to reject this proposal as a result.

If you wanted, feel free to release a gem `inflecto-refinements` that provides this feature as an opt-in for users. I'd be willing to link to it in the README.

**Comment by alsemyonov** [comment]
Ok, let me do that.

**Comment by alsemyonov** [comment]
Done: 

* Gem: https://rubygems.org/gems/inflecto-refinements
* Code: https://github.com/alsemyonov/inflecto-refinements

**Comment by mbj** [comment]
@alsemyonov Do you want to PR the readme addition?

**Pull request closed without merging**
